# Generated by Django 5.0.7 on 2024-11-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='short_description_banner_de',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='short_description_banner_en',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='title_de',
            field=models.CharField(db_index=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='title_en',
            field=models.CharField(db_index=True, max_length=300, null=True),
        ),
    ]
