# Generated by Django 5.0.7 on 2024-11-11 17:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLinkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('url_title', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='images/site_logo/')),
                ('is_main_setting', models.BooleanField(default=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('phone', models.CharField(blank=True, max_length=31, null=True)),
                ('fax', models.CharField(blank=True, max_length=31, null=True)),
                ('email', models.EmailField(blank=True, max_length=31, null=True)),
                ('copy_right', models.TextField(blank=True, null=True)),
                ('about_us', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('site_name', models.CharField(max_length=150)),
                ('site_url', models.CharField(max_length=255)),
            ],
        ),
    ]
